# 2017-12-03  William A. Hudson

# Run all test suites.

PATH = /usr/bin:/bin

SHELL = /bin/sh

test:
	cd t_Error            && make test
	cd t_yBuffStat        && make test
	cd t_yCoeffItr        && make test
	cd t_yFramDat         && make test
#	cd t_utLib1           && make test

clean:
	cd t_Error            && make clean
	cd t_yBuffStat        && make clean
	cd t_yCoeffItr        && make clean
	cd t_yFramDat         && make clean
#	cd t_utLib1           && make clean

